services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ofs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ofs-frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
    command: npm run dev

  backend:
    build:
      context: ./ofs-backend
      dockerfile: dockerfile
    container_name: ofs-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ofs-backend:/app
